apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: games-kwathu-cert
  namespace: doorbell
spec:
  secretName: games-kwathu-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - games.kwathu.ai
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
